### ISSUE TITLE
ストアに公開する予定はありますか？

### ISSUE THREAD

**Issue by daruyanagi** [osamum/textSpeech_exteneion_for_MSEdge#4]
T/O

**Comment by osamum** [comment]
以下のQA サイトにあるように現在はまだストアのほうが Edge の拡張を受け付けていないので、オープンしたら提出しようと思っております。
https://developer.microsoft.com/en-us/microsoft-edge/platform/faq/
その前に以下の点を改修する予定です。

・国際化対応
・オプションページのデザイン見直し

その他、Windows 10 のフィードバック Hub などに寄せられている機能要望で、拡張でどうにかできそうなものは作ってしまおうかな、と。(時間はこれから捻出します

**Comment by daruyanagi** [comment]
では楽しみにしています～

**Comment by osamum** [comment]
だるやなぎさんもぜひ、こんな機能があったらいいな～、というのがありましたら作成をお願いします～
